package com.itqf.dtboot.entity;

import java.io.Serializable;

public class City implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_name
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_introduce
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private String cityIntroduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_strategy
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private String cityStrategy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.img
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.slogn
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private String slogn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.recommend
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private String recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table city
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_id
     *
     * @return the value of city.city_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_id
     *
     * @param cityId the value for city.city_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_name
     *
     * @return the value of city.city_name
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_name
     *
     * @param cityName the value for city.city_name
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_introduce
     *
     * @return the value of city.city_introduce
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public String getCityIntroduce() {
        return cityIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_introduce
     *
     * @param cityIntroduce the value for city.city_introduce
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setCityIntroduce(String cityIntroduce) {
        this.cityIntroduce = cityIntroduce == null ? null : cityIntroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_strategy
     *
     * @return the value of city.city_strategy
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public String getCityStrategy() {
        return cityStrategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_strategy
     *
     * @param cityStrategy the value for city.city_strategy
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setCityStrategy(String cityStrategy) {
        this.cityStrategy = cityStrategy == null ? null : cityStrategy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.img
     *
     * @return the value of city.img
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.img
     *
     * @param img the value for city.img
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.slogn
     *
     * @return the value of city.slogn
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public String getSlogn() {
        return slogn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.slogn
     *
     * @param slogn the value for city.slogn
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setSlogn(String slogn) {
        this.slogn = slogn == null ? null : slogn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city
     *
     * @return the value of city.city
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city
     *
     * @param city the value for city.city
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.recommend
     *
     * @return the value of city.recommend
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public String getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.recommend
     *
     * @param recommend the value for city.recommend
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setRecommend(String recommend) {
        this.recommend = recommend == null ? null : recommend.trim();
    }
}