package com.itqf.dtboot.entity;

import java.io.Serializable;

public class Collection implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.colt_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private Integer coltId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.user_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.combo_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private Integer comboId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table collection
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.colt_id
     *
     * @return the value of collection.colt_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public Integer getColtId() {
        return coltId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.colt_id
     *
     * @param coltId the value for collection.colt_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setColtId(Integer coltId) {
        this.coltId = coltId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.user_id
     *
     * @return the value of collection.user_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.user_id
     *
     * @param userId the value for collection.user_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.combo_id
     *
     * @return the value of collection.combo_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public Integer getComboId() {
        return comboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.combo_id
     *
     * @param comboId the value for collection.combo_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setComboId(Integer comboId) {
        this.comboId = comboId;
    }
}