package com.itqf.dtboot.entity;

import java.io.Serializable;

public class Diet implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diet.id
     *
     * @mbggenerated Wed Feb 20 16:48:03 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diet.name
     *
     * @mbggenerated Wed Feb 20 16:48:03 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diet.price
     *
     * @mbggenerated Wed Feb 20 16:48:03 CST 2019
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table diet
     *
     * @mbggenerated Wed Feb 20 16:48:03 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diet.id
     *
     * @return the value of diet.id
     *
     * @mbggenerated Wed Feb 20 16:48:03 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diet.id
     *
     * @param id the value for diet.id
     *
     * @mbggenerated Wed Feb 20 16:48:03 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diet.name
     *
     * @return the value of diet.name
     *
     * @mbggenerated Wed Feb 20 16:48:03 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diet.name
     *
     * @param name the value for diet.name
     *
     * @mbggenerated Wed Feb 20 16:48:03 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diet.price
     *
     * @return the value of diet.price
     *
     * @mbggenerated Wed Feb 20 16:48:03 CST 2019
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diet.price
     *
     * @param price the value for diet.price
     *
     * @mbggenerated Wed Feb 20 16:48:03 CST 2019
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }
}