package com.itqf.dtboot.entity;

import java.io.Serializable;

public class Photographer implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photographer.id
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photographer.name
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photographer.price
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table photographer
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photographer.id
     *
     * @return the value of photographer.id
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photographer.id
     *
     * @param id the value for photographer.id
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photographer.name
     *
     * @return the value of photographer.name
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photographer.name
     *
     * @param name the value for photographer.name
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photographer.price
     *
     * @return the value of photographer.price
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photographer.price
     *
     * @param price the value for photographer.price
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}