package com.itqf.dtboot.entity;

import java.io.Serializable;

public class Phototeam implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phototeam.team_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private Integer teamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phototeam.team_name
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private String teamName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phototeam.team_price
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private Double teamPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phototeam.team_score
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private Double teamScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phototeam.name
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phototeam.price
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table phototeam
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phototeam.team_id
     *
     * @return the value of phototeam.team_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public Integer getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phototeam.team_id
     *
     * @param teamId the value for phototeam.team_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phototeam.team_name
     *
     * @return the value of phototeam.team_name
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phototeam.team_name
     *
     * @param teamName the value for phototeam.team_name
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setTeamName(String teamName) {
        this.teamName = teamName == null ? null : teamName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phototeam.team_price
     *
     * @return the value of phototeam.team_price
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public Double getTeamPrice() {
        return teamPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phototeam.team_price
     *
     * @param teamPrice the value for phototeam.team_price
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setTeamPrice(Double teamPrice) {
        this.teamPrice = teamPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phototeam.team_score
     *
     * @return the value of phototeam.team_score
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public Double getTeamScore() {
        return teamScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phototeam.team_score
     *
     * @param teamScore the value for phototeam.team_score
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setTeamScore(Double teamScore) {
        this.teamScore = teamScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phototeam.name
     *
     * @return the value of phototeam.name
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phototeam.name
     *
     * @param name the value for phototeam.name
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phototeam.price
     *
     * @return the value of phototeam.price
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phototeam.price
     *
     * @param price the value for phototeam.price
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }
}