package com.itqf.dtboot.entity;

import java.io.Serializable;

public class Restaurant implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.rest_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private Integer restId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.hotel_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private Integer hotelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.site_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private Integer siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.rest_img
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private String restImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.rest_price
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private Double restPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table restaurant
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.rest_id
     *
     * @return the value of restaurant.rest_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public Integer getRestId() {
        return restId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.rest_id
     *
     * @param restId the value for restaurant.rest_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setRestId(Integer restId) {
        this.restId = restId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.hotel_id
     *
     * @return the value of restaurant.hotel_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.hotel_id
     *
     * @param hotelId the value for restaurant.hotel_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.site_id
     *
     * @return the value of restaurant.site_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.site_id
     *
     * @param siteId the value for restaurant.site_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.rest_img
     *
     * @return the value of restaurant.rest_img
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public String getRestImg() {
        return restImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.rest_img
     *
     * @param restImg the value for restaurant.rest_img
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setRestImg(String restImg) {
        this.restImg = restImg == null ? null : restImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.rest_price
     *
     * @return the value of restaurant.rest_price
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public Double getRestPrice() {
        return restPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.rest_price
     *
     * @param restPrice the value for restaurant.rest_price
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setRestPrice(Double restPrice) {
        this.restPrice = restPrice;
    }
}