package com.itqf.dtboot.entity;

import java.io.Serializable;

public class SysConfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.fb_id
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private Integer fbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.fb_content
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private String fbContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.fb_telphone
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private String fbTelphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.fb_userid
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private Integer fbUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table feedback
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.fb_id
     *
     * @return the value of feedback.fb_id
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public Integer getFbId() {
        return fbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.fb_id
     *
     * @param fbId the value for feedback.fb_id
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setFbId(Integer fbId) {
        this.fbId = fbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.fb_content
     *
     * @return the value of feedback.fb_content
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public String getFbContent() {
        return fbContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.fb_content
     *
     * @param fbContent the value for feedback.fb_content
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setFbContent(String fbContent) {
        this.fbContent = fbContent == null ? null : fbContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.fb_telphone
     *
     * @return the value of feedback.fb_telphone
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public String getFbTelphone() {
        return fbTelphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.fb_telphone
     *
     * @param fbTelphone the value for feedback.fb_telphone
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setFbTelphone(String fbTelphone) {
        this.fbTelphone = fbTelphone == null ? null : fbTelphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.fb_userid
     *
     * @return the value of feedback.fb_userid
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public Integer getFbUserid() {
        return fbUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.fb_userid
     *
     * @param fbUserid the value for feedback.fb_userid
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setFbUserid(Integer fbUserid) {
        this.fbUserid = fbUserid;
    }
}