package com.itqf.dtboot.entity;

import java.io.Serializable;

public class SysLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.hotel_id
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private Integer hotelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.site_id
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private Integer siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.city_id
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.hotel_img
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private String hotelImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.hotel_price
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private Double hotelPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.hotel_id
     *
     * @return the value of hotel.hotel_id
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.hotel_id
     *
     * @param hotelId the value for hotel.hotel_id
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.site_id
     *
     * @return the value of hotel.site_id
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.site_id
     *
     * @param siteId the value for hotel.site_id
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.city_id
     *
     * @return the value of hotel.city_id
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.city_id
     *
     * @param cityId the value for hotel.city_id
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.hotel_img
     *
     * @return the value of hotel.hotel_img
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public String getHotelImg() {
        return hotelImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.hotel_img
     *
     * @param hotelImg the value for hotel.hotel_img
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setHotelImg(String hotelImg) {
        this.hotelImg = hotelImg == null ? null : hotelImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.hotel_price
     *
     * @return the value of hotel.hotel_price
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public Double getHotelPrice() {
        return hotelPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.hotel_price
     *
     * @param hotelPrice the value for hotel.hotel_price
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setHotelPrice(Double hotelPrice) {
        this.hotelPrice = hotelPrice;
    }
}