package com.itqf.dtboot.entity;

import java.io.Serializable;

public class SysMenu implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_id
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_name
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_introduce
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private String cityIntroduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_strategy
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private String cityStrategy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table city
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_id
     *
     * @return the value of city.city_id
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_id
     *
     * @param cityId the value for city.city_id
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_name
     *
     * @return the value of city.city_name
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_name
     *
     * @param cityName the value for city.city_name
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_introduce
     *
     * @return the value of city.city_introduce
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public String getCityIntroduce() {
        return cityIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_introduce
     *
     * @param cityIntroduce the value for city.city_introduce
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setCityIntroduce(String cityIntroduce) {
        this.cityIntroduce = cityIntroduce == null ? null : cityIntroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_strategy
     *
     * @return the value of city.city_strategy
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public String getCityStrategy() {
        return cityStrategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_strategy
     *
     * @param cityStrategy the value for city.city_strategy
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setCityStrategy(String cityStrategy) {
        this.cityStrategy = cityStrategy == null ? null : cityStrategy.trim();
    }
}