package com.itqf.dtboot.entity;

import java.io.Serializable;
import java.util.Date;

public class SysRoleMenu implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column combo_evaluate.ev_id
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private Integer evId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column combo_evaluate.ev_content
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private String evContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column combo_evaluate.ev_url
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private String evUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column combo_evaluate.ev_time
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private Date evTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table combo_evaluate
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column combo_evaluate.ev_id
     *
     * @return the value of combo_evaluate.ev_id
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public Integer getEvId() {
        return evId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column combo_evaluate.ev_id
     *
     * @param evId the value for combo_evaluate.ev_id
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setEvId(Integer evId) {
        this.evId = evId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column combo_evaluate.ev_content
     *
     * @return the value of combo_evaluate.ev_content
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public String getEvContent() {
        return evContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column combo_evaluate.ev_content
     *
     * @param evContent the value for combo_evaluate.ev_content
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setEvContent(String evContent) {
        this.evContent = evContent == null ? null : evContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column combo_evaluate.ev_url
     *
     * @return the value of combo_evaluate.ev_url
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public String getEvUrl() {
        return evUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column combo_evaluate.ev_url
     *
     * @param evUrl the value for combo_evaluate.ev_url
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setEvUrl(String evUrl) {
        this.evUrl = evUrl == null ? null : evUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column combo_evaluate.ev_time
     *
     * @return the value of combo_evaluate.ev_time
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public Date getEvTime() {
        return evTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column combo_evaluate.ev_time
     *
     * @param evTime the value for combo_evaluate.ev_time
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setEvTime(Date evTime) {
        this.evTime = evTime;
    }
}