package com.itqf.dtboot.entity;

import java.io.Serializable;

public class SysUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column combo.combo_id
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private Integer comboId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column combo.combo_name
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private String comboName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column combo.combo_tagname
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private String comboTagname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column combo.combo_price
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private Double comboPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column combo.combo_shared
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private Integer comboShared;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column combo.combo_search
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private Integer comboSearch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column combo.combo_reserve
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private String comboReserve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column combo.combo_imgid
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private String comboImgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column combo.combo_shid
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private Integer comboShid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column combo.combo_descid
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private String comboDescid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column combo.combo_evaluateid
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private Integer comboEvaluateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table combo
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column combo.combo_id
     *
     * @return the value of combo.combo_id
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public Integer getComboId() {
        return comboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column combo.combo_id
     *
     * @param comboId the value for combo.combo_id
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setComboId(Integer comboId) {
        this.comboId = comboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column combo.combo_name
     *
     * @return the value of combo.combo_name
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public String getComboName() {
        return comboName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column combo.combo_name
     *
     * @param comboName the value for combo.combo_name
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setComboName(String comboName) {
        this.comboName = comboName == null ? null : comboName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column combo.combo_tagname
     *
     * @return the value of combo.combo_tagname
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public String getComboTagname() {
        return comboTagname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column combo.combo_tagname
     *
     * @param comboTagname the value for combo.combo_tagname
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setComboTagname(String comboTagname) {
        this.comboTagname = comboTagname == null ? null : comboTagname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column combo.combo_price
     *
     * @return the value of combo.combo_price
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public Double getComboPrice() {
        return comboPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column combo.combo_price
     *
     * @param comboPrice the value for combo.combo_price
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setComboPrice(Double comboPrice) {
        this.comboPrice = comboPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column combo.combo_shared
     *
     * @return the value of combo.combo_shared
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public Integer getComboShared() {
        return comboShared;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column combo.combo_shared
     *
     * @param comboShared the value for combo.combo_shared
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setComboShared(Integer comboShared) {
        this.comboShared = comboShared;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column combo.combo_search
     *
     * @return the value of combo.combo_search
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public Integer getComboSearch() {
        return comboSearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column combo.combo_search
     *
     * @param comboSearch the value for combo.combo_search
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setComboSearch(Integer comboSearch) {
        this.comboSearch = comboSearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column combo.combo_reserve
     *
     * @return the value of combo.combo_reserve
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public String getComboReserve() {
        return comboReserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column combo.combo_reserve
     *
     * @param comboReserve the value for combo.combo_reserve
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setComboReserve(String comboReserve) {
        this.comboReserve = comboReserve == null ? null : comboReserve.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column combo.combo_imgid
     *
     * @return the value of combo.combo_imgid
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public String getComboImgid() {
        return comboImgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column combo.combo_imgid
     *
     * @param comboImgid the value for combo.combo_imgid
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setComboImgid(String comboImgid) {
        this.comboImgid = comboImgid == null ? null : comboImgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column combo.combo_shid
     *
     * @return the value of combo.combo_shid
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public Integer getComboShid() {
        return comboShid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column combo.combo_shid
     *
     * @param comboShid the value for combo.combo_shid
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setComboShid(Integer comboShid) {
        this.comboShid = comboShid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column combo.combo_descid
     *
     * @return the value of combo.combo_descid
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public String getComboDescid() {
        return comboDescid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column combo.combo_descid
     *
     * @param comboDescid the value for combo.combo_descid
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setComboDescid(String comboDescid) {
        this.comboDescid = comboDescid == null ? null : comboDescid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column combo.combo_evaluateid
     *
     * @return the value of combo.combo_evaluateid
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public Integer getComboEvaluateid() {
        return comboEvaluateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column combo.combo_evaluateid
     *
     * @param comboEvaluateid the value for combo.combo_evaluateid
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setComboEvaluateid(Integer comboEvaluateid) {
        this.comboEvaluateid = comboEvaluateid;
    }
}