package com.itqf.dtboot.entity;

import java.io.Serializable;

public class SysUserRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.f_id
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private Integer fId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.f_useid
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private Integer fUseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.f_fansid
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private Integer fFansid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fans
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.f_id
     *
     * @return the value of fans.f_id
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public Integer getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.f_id
     *
     * @param fId the value for fans.f_id
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setfId(Integer fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.f_useid
     *
     * @return the value of fans.f_useid
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public Integer getfUseid() {
        return fUseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.f_useid
     *
     * @param fUseid the value for fans.f_useid
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setfUseid(Integer fUseid) {
        this.fUseid = fUseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.f_fansid
     *
     * @return the value of fans.f_fansid
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public Integer getfFansid() {
        return fFansid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.f_fansid
     *
     * @param fFansid the value for fans.f_fansid
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    public void setfFansid(Integer fFansid) {
        this.fFansid = fFansid;
    }
}