package com.itqf.dtboot.entity;

import java.io.Serializable;

public class Traffic implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic.id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic.name
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic.price
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table traffic
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic.id
     *
     * @return the value of traffic.id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic.id
     *
     * @param id the value for traffic.id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic.name
     *
     * @return the value of traffic.name
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic.name
     *
     * @param name the value for traffic.name
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic.price
     *
     * @return the value of traffic.price
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic.price
     *
     * @param price the value for traffic.price
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}