package com.itqf.dtboot.entity;

import java.io.Serializable;
import java.util.Date;

public class TravelComment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_comment.comt_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private Integer comtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_comment.comt_tid
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private Integer comtTid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_comment.comt_userid
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private Integer comtUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_comment.comt_detail
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private String comtDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_comment.comt_time
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private Date comtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table travel_comment
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_comment.comt_id
     *
     * @return the value of travel_comment.comt_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public Integer getComtId() {
        return comtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_comment.comt_id
     *
     * @param comtId the value for travel_comment.comt_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setComtId(Integer comtId) {
        this.comtId = comtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_comment.comt_tid
     *
     * @return the value of travel_comment.comt_tid
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public Integer getComtTid() {
        return comtTid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_comment.comt_tid
     *
     * @param comtTid the value for travel_comment.comt_tid
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setComtTid(Integer comtTid) {
        this.comtTid = comtTid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_comment.comt_userid
     *
     * @return the value of travel_comment.comt_userid
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public Integer getComtUserid() {
        return comtUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_comment.comt_userid
     *
     * @param comtUserid the value for travel_comment.comt_userid
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setComtUserid(Integer comtUserid) {
        this.comtUserid = comtUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_comment.comt_detail
     *
     * @return the value of travel_comment.comt_detail
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public String getComtDetail() {
        return comtDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_comment.comt_detail
     *
     * @param comtDetail the value for travel_comment.comt_detail
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setComtDetail(String comtDetail) {
        this.comtDetail = comtDetail == null ? null : comtDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_comment.comt_time
     *
     * @return the value of travel_comment.comt_time
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public Date getComtTime() {
        return comtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_comment.comt_time
     *
     * @param comtTime the value for travel_comment.comt_time
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setComtTime(Date comtTime) {
        this.comtTime = comtTime;
    }
}