package com.itqf.dtboot.entity;

import java.io.Serializable;
import java.util.Date;

public class Travel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel.t_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private Integer tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel.t_userid
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private Integer tUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel.t_title
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private String tTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel.t_content
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private String tContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel.t_time
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private Date tTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel.t_city
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private String tCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel.t_img
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private String tImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel.retr_cid
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private String retrCid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel.retr_poum
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private String retrPoum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel.travelcol
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private String travelcol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table travel
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel.t_id
     *
     * @return the value of travel.t_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel.t_id
     *
     * @param tId the value for travel.t_id
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel.t_userid
     *
     * @return the value of travel.t_userid
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public Integer gettUserid() {
        return tUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel.t_userid
     *
     * @param tUserid the value for travel.t_userid
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void settUserid(Integer tUserid) {
        this.tUserid = tUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel.t_title
     *
     * @return the value of travel.t_title
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public String gettTitle() {
        return tTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel.t_title
     *
     * @param tTitle the value for travel.t_title
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void settTitle(String tTitle) {
        this.tTitle = tTitle == null ? null : tTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel.t_content
     *
     * @return the value of travel.t_content
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public String gettContent() {
        return tContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel.t_content
     *
     * @param tContent the value for travel.t_content
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void settContent(String tContent) {
        this.tContent = tContent == null ? null : tContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel.t_time
     *
     * @return the value of travel.t_time
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public Date gettTime() {
        return tTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel.t_time
     *
     * @param tTime the value for travel.t_time
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void settTime(Date tTime) {
        this.tTime = tTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel.t_city
     *
     * @return the value of travel.t_city
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public String gettCity() {
        return tCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel.t_city
     *
     * @param tCity the value for travel.t_city
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void settCity(String tCity) {
        this.tCity = tCity == null ? null : tCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel.t_img
     *
     * @return the value of travel.t_img
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public String gettImg() {
        return tImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel.t_img
     *
     * @param tImg the value for travel.t_img
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void settImg(String tImg) {
        this.tImg = tImg == null ? null : tImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel.retr_cid
     *
     * @return the value of travel.retr_cid
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public String getRetrCid() {
        return retrCid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel.retr_cid
     *
     * @param retrCid the value for travel.retr_cid
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setRetrCid(String retrCid) {
        this.retrCid = retrCid == null ? null : retrCid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel.retr_poum
     *
     * @return the value of travel.retr_poum
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public String getRetrPoum() {
        return retrPoum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel.retr_poum
     *
     * @param retrPoum the value for travel.retr_poum
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setRetrPoum(String retrPoum) {
        this.retrPoum = retrPoum == null ? null : retrPoum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel.travelcol
     *
     * @return the value of travel.travelcol
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public String getTravelcol() {
        return travelcol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel.travelcol
     *
     * @param travelcol the value for travel.travelcol
     *
     * @mbggenerated Wed Feb 20 16:42:06 CST 2019
     */
    public void setTravelcol(String travelcol) {
        this.travelcol = travelcol == null ? null : travelcol.trim();
    }
}