package com.itqf.dtboot.dao;

import com.itqf.dtboot.entity.Combo;

import java.util.List;

public interface ComboMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table combo
     *
     * @mbggenerated Wed Feb 20 15:31:07 CST 2019
     */
    int deleteByPrimaryKey(Integer comboId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table combo
     *
     * @mbggenerated Wed Feb 20 15:31:07 CST 2019
     */
    int insert(Combo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table combo
     *
     * @mbggenerated Wed Feb 20 15:31:07 CST 2019
     */
    int insertSelective(Combo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table combo
     *
     * @mbggenerated Wed Feb 20 15:31:07 CST 2019
     */
    Combo selectByPrimaryKey(Integer comboId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table combo
     *
     * @mbggenerated Wed Feb 20 15:31:07 CST 2019
     */
    int updateByPrimaryKeySelective(Combo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table combo
     *
     * @mbggenerated Wed Feb 20 15:31:07 CST 2019
     */
    int updateByPrimaryKey(Combo record);
    List<Combo> selectAll();
}