package com.itqf.dtboot.dao;

import com.itqf.dtboot.entity.ComboEvaluate;

public interface ComboEvaluateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table combo_evaluate
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int deleteByPrimaryKey(Integer evId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table combo_evaluate
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int insert(ComboEvaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table combo_evaluate
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int insertSelective(ComboEvaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table combo_evaluate
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    ComboEvaluate selectByPrimaryKey(Integer evId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table combo_evaluate
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int updateByPrimaryKeySelective(ComboEvaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table combo_evaluate
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int updateByPrimaryKey(ComboEvaluate record);
}