package com.itqf.dtboot.dao;

import com.itqf.dtboot.entity.Diet;

import java.util.List;

public interface DietMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diet
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diet
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    int insert(Diet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diet
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    int insertSelective(Diet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diet
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    Diet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diet
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    int updateByPrimaryKeySelective(Diet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diet
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    int updateByPrimaryKey(Diet record);

    List<Diet> findAll();
}