package com.itqf.dtboot.dao;

import com.itqf.dtboot.entity.Hotel;

import java.util.List;

public interface HotelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    int deleteByPrimaryKey(Integer hotelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    int insert(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    int insertSelective(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    Hotel selectByPrimaryKey(Integer hotelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    int updateByPrimaryKeySelective(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    int updateByPrimaryKey(Hotel record);
    List<Hotel> findAll();
}