package com.itqf.dtboot.dao;

import com.itqf.dtboot.entity.Phototeam;

import java.util.List;

public interface PhototeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phototeam
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int deleteByPrimaryKey(Integer teamId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phototeam
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int insert(Phototeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phototeam
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int insertSelective(Phototeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phototeam
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    Phototeam selectByPrimaryKey(Integer teamId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phototeam
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int updateByPrimaryKeySelective(Phototeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phototeam
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int updateByPrimaryKey(Phototeam record);
    List<Phototeam> findAll();
}