package com.itqf.dtboot.dao;

import com.itqf.dtboot.entity.Photographer;

import java.util.List;

public interface PhotographerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photographer
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photographer
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    int insert(Photographer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photographer
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    int insertSelective(Photographer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photographer
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    Photographer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photographer
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    int updateByPrimaryKeySelective(Photographer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photographer
     *
     * @mbggenerated Wed Feb 20 16:49:46 CST 2019
     */
    int updateByPrimaryKey(Photographer record);
    List<Photographer> findAll();
}