package com.itqf.dtboot.dao;

import com.itqf.dtboot.entity.SysRole;

public interface SysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    int deleteByPrimaryKey(Integer coltId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    int insert(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    int insertSelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    SysRole selectByPrimaryKey(Integer coltId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    int updateByPrimaryKeySelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    int updateByPrimaryKey(SysRole record);
}