package com.itqf.dtboot.dao;

import com.itqf.dtboot.entity.SysUser;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table combo
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    int deleteByPrimaryKey(Integer comboId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table combo
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table combo
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table combo
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    SysUser selectByPrimaryKey(Integer comboId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table combo
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table combo
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    int updateByPrimaryKey(SysUser record);
}