package com.itqf.dtboot.dao;

import com.itqf.dtboot.entity.TbToken;

public interface TbTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_travel
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    int deleteByPrimaryKey(Integer utId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_travel
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    int insert(TbToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_travel
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    int insertSelective(TbToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_travel
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    TbToken selectByPrimaryKey(Integer utId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_travel
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    int updateByPrimaryKeySelective(TbToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_travel
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    int updateByPrimaryKey(TbToken record);
}