package com.itqf.dtboot.dao;

import com.itqf.dtboot.entity.TbUser;

public interface TbUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    int deleteByPrimaryKey(Integer restId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    int insert(TbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    int insertSelective(TbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    TbUser selectByPrimaryKey(Integer restId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    int updateByPrimaryKeySelective(TbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbggenerated Thu Jan 24 10:07:32 CST 2019
     */
    int updateByPrimaryKey(TbUser record);
}