package com.itqf.dtboot.dao;

import com.itqf.dtboot.entity.Traffic;

import java.util.List;

public interface TrafficMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic
     *
     * @mbggenerated Sat Feb 16 10:19:57 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic
     *
     * @mbggenerated Sat Feb 16 10:19:57 CST 2019
     */
    int insert(Traffic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic
     *
     * @mbggenerated Sat Feb 16 10:19:57 CST 2019
     */
    int insertSelective(Traffic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic
     *
     * @mbggenerated Sat Feb 16 10:19:57 CST 2019
     */
    Traffic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic
     *
     * @mbggenerated Sat Feb 16 10:19:57 CST 2019
     */
    int updateByPrimaryKeySelective(Traffic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic
     *
     * @mbggenerated Sat Feb 16 10:19:57 CST 2019
     */
    int updateByPrimaryKey(Traffic record);
    List<Traffic> findAll();
}