package com.itqf.dtboot.dao;

import com.itqf.dtboot.entity.Travel;

public interface TravelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int deleteByPrimaryKey(Integer tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int insert(Travel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int insertSelective(Travel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    Travel selectByPrimaryKey(Integer tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int updateByPrimaryKeySelective(Travel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int updateByPrimaryKey(Travel record);
}