package com.itqf.dtboot.dao;

import com.itqf.dtboot.entity.TravelComment;

public interface TravelCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_comment
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int deleteByPrimaryKey(Integer comtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_comment
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int insert(TravelComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_comment
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int insertSelective(TravelComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_comment
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    TravelComment selectByPrimaryKey(Integer comtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_comment
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int updateByPrimaryKeySelective(TravelComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_comment
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int updateByPrimaryKey(TravelComment record);
}