package com.itqf.dtboot.dao;

import com.itqf.dtboot.entity.UserTravel;

public interface UserTravelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_travel
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int deleteByPrimaryKey(Integer utId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_travel
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int insert(UserTravel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_travel
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int insertSelective(UserTravel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_travel
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    UserTravel selectByPrimaryKey(Integer utId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_travel
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int updateByPrimaryKeySelective(UserTravel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_travel
     *
     * @mbggenerated Wed Feb 13 10:31:33 CST 2019
     */
    int updateByPrimaryKey(UserTravel record);
}